### ISSUE TITLE
Make contact form ajax

### ISSUE THREAD

**Issue by kyletaylored** [techmilldenton/hackntx#29]
https://codepen.io/daveguck/pen/meameV

**Comment by newswim** [comment]
According to their site, this is only available to Formspree Gold users. Might not actually be the case, but seems to be their intention.

**Comment by sffitzpatrick** [comment]
@kyletaylored @newswim Hey guys, what's up? I started looking at this Saturday after Kyle posted something about this issue queue on Slack. Dan is right that this doesn't seem to work without the gold-level account at formspree. I have some working code to prove this doesn't work :). I'll push up a PR that you can grab if you ever get a gold account. 

I'll try to grab other issues here too. I ❤️ jekyll.

**Comment by kyletaylored** [comment]
Closed with #40
