### ISSUE TITLE
Add social links to sponsors

### ISSUE THREAD

**Issue by kyletaylored** [techmilldenton/hackntx#38]
Add slots for social and web links under each sponsor.

- Website link
- Twitter
- Facebook
- LinkedIn

**Comment by sffitzpatrick** [comment]
Is this ready to work on or is #35 a dependency for this?

**Comment by kyletaylored** [comment]
> Is this ready to work on or is #35 a dependency for this?

Yep, #35 is a dependency.

**Comment by RCulpepp** [comment]
#53 merge request submitted

**Comment by kyletaylored** [comment]
Fixed by #53
