### ISSUE TITLE
add a readme

### ISSUE THREAD

**Issue by sffitzpatrick** [techmilldenton/hackntx#41]
Hey guys, I wanted to add a readme, mainly for contributors at this point. This might need some clarification. I wasn't sure if there's a need for Gulp here when Jekyll is compiling scss.

**Comment by kyletaylored** [comment]
Yea, the theme we're using had Gulp included for compiling assets, but it seemed more straight forward to just use Jekyll Sass compiling instead. Maybe at some point we can set up a Gulp task to watch assets and start a Jekyll server at the same time
