### ISSUE TITLE
Create notification event system

### ISSUE THREAD

**Issue by kyletaylored** [techmilldenton/hackntx#50]
This sounds bigger than it is - but for example, if someone donates through our Paypal links, there's a redirect with a query parameter. I'd like a common function we can use to interpret that query param and display a notification or alert on the page with a piece of content.

Here's an example: https://www.hackntx.com/contact?thankyou=1

Ideally, we could have a YAML file of items that contain the query key, value, and color option (success, alert, etc), that gets converted to JSON and the script just looks for a match and plops it into a template.

You can find the current code in `/assets/js/custom.js`

**Comment by kyletaylored** [comment]
A modal option might be nice too. Maybe one of the options could be "type" with `alert` or `modal` as options.

**Comment by sffitzpatrick** [comment]
@kyletaylored this sounds good. If I'm understanding this right I think the JSON would be at a public URL (hackntx.com/messages.json or whatever)... is that OK? Then a script can key off the param and load up whatever content from the JSON. This sounds pretty straightforward.

**Comment by kyletaylored** [comment]
Yep! Maybe we can update robots.txt to ignore it (not that it matters). And since Jekyll will compile any file in the directory, you could convert the YML list into a JSON file using Liquid loops.
