### ISSUE TITLE
A few bugs in mobile view

### ISSUE THREAD

**Issue by newswim** [techmilldenton/hackntx#58]
Here are some screenshots from my iPhone X.

![02aced25-632a-419f-bd59-e98958ab0629](https://user-images.githubusercontent.com/6667096/47599514-54afab80-d975-11e8-9c84-ed0a92b7c408.png)
![dc91434a-c2a4-439e-9179-eda39aa96601](https://user-images.githubusercontent.com/6667096/47599515-54afab80-d975-11e8-82fe-5a4fdde708db.png)

**Comment by newswim** [comment]
To recap:

- Hero text needs top margin in mobile views (and testing on other devices)
- Map component needs a max-width rule

**Comment by sffitzpatrick** [comment]
I can fix this tomorrow (Tuesday). BUT I won't officially assign it to myself yet in case anyone else wants to take it before I get to it.

**Comment by sffitzpatrick** [comment]
see #59

**Comment by newswim** [comment]
❤️
